import {ManualData} from "./man-data";

const BASE_GAME_ACCOMPANYING_BOOKLET: string = "Begleitheft - Orginalspiel";
const GEAR_CARD_BASE_GAME: string = "Ausrüstungstafel Basisspiel";

const baseGameBookletData: ManualData[] = [
	{
		id: "gors",
		title: "Gor",
		images: ["/og-booklet/creatures-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`],
	},
	{
		id: "skrals",
		title: "Skral",
		images: ["/og-booklet/creatures-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`],
	},
	{
		id: "troll",
		title: "Troll",
		images: ["/og-booklet/creatures-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`],
	},
	{
		id: "wardraks",
		title: "Wardraks",
		images: ["/og-booklet/creatures-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`],
	},
	{
		id: "dark-mage",
		title: "Dunkler Magier",
		images: ["/og-booklet/other-figures-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`],
	},
	{
		id: "story-teller",
		title: "Erzähler",
		images: ["/og-booklet/other-figures-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`],
	},
	{
		id: "tower",
		title: "Turm",
		images: ["/og-booklet/other-figures-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`],
	},
	{
		id: "dragon",
		title: "Drache",
		images: ["/og-booklet/other-figures-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`],
	},
	{
		id: "silver-start-event-card",
		title: "Silberne Start-Ereigniskarte",
		images: ["/og-booklet/event-cards-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`],
	},
	{
		id: "silver-event-card",
		title: "Silberne Ereigniskarte",
		images: ["/og-booklet/event-cards-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`],
	},
	{
		id: "gold-event-card",
		title: "Goldene Ereigniskarte",
		images: ["/og-booklet/event-cards-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`],
	},
	{
		id: "event-card-secret-lake",
		title: "Ereigniskarte 'Geheimer See'",
		images: ["/og-booklet/event-cards-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`],
	},
	{
		id: "fate-card",
		title: "Schicksalskarte",
		images: ["/og-booklet/event-cards-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`],
	},
	{
		id: "heroes",
		title: "Helden",
		images: ["/og-booklet/heroes-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`],
	},
	{
		id: "gold",
		title: "Goldplättchen",
		images: ["/og-booklet/gold-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`],
	},
	{
		id: "poison",
		title: "Gift",
		images: ["/og-booklet/poison-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`],
	},
	{
		id: "star",
		title: "Sternchen",
		images: ["/og-booklet/star-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`],
	},
	{
		id: "well",
		title: "Brunnenplättchen",
		images: ["/og-booklet/well-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`],
	},
	{
		id: "rubble",
		title: "Geröllplättchen",
		images: ["/og-booklet/rubble-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`],
	},
	{
		id: "parchment",
		title: "Pergamente",
		images: ["/og-booklet/parchment-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`],
	},
	{
		id: "gems",
		title: "Edelsteine",
		images: ["/og-booklet/gems-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`],
	},
	{
		id: "red-x",
		title: "Rotes X",
		images: ["/og-booklet/red-x-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`],
	},
	{
		id: "gear",
		title: "(Ausrüstungs-) Gegenstände",
		images: ["/og-booklet/gear-i0.png", "/gear-card-base-game/gear-card-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`, GEAR_CARD_BASE_GAME],
	},
	{
		id: "creature-platelets",
		title: "Kreaturenplättchen",
		images: ["/og-booklet/creature-platelets-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`],
	},
	{
		id: "n-platelets",
		title: "'N'-Plättchen",
		images: ["/og-booklet/n-platelets-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`],
	},
	{
		id: "hero-actions",
		title: "Aktionen der Helden",
		images: ["/og-booklet/hero-actions-rt0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 2`],
	},
	{
		id: "course-of-a-fight",
		title: "Ablauf eines Kampfes",
		images: ["/og-booklet/course-of-fight-rt0.png", "/og-booklet/course-of-fight-rt1.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 2`],
	},
	{
		id: "farmers",
		title: "Bauern",
		images: ["/og-booklet/farmers-rt0.png", "/og-booklet/farmers-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 3`],
	},
	{
		id: "creature-movement",
		title: "Bewegung der Kreaturen",
		images: ["/og-booklet/creature-movement-rt0.png", "/og-booklet/creature-movement-rt1.png", "/og-booklet/creatures-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 2/3`],
	},
	{
		id: "healing-herbs",
		title: "Heilkräuter",
		images: ["/og-booklet/healing-herbs-rt0.png", "/og-booklet/healing-herbs-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 3`],
	},
	{
		id: "fog-platelets",
		title: "Nebelplättchen",
		images: ["/og-booklet/fog-platelets-rt0.png", "/og-booklet/fog-platelets-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 3`],
	},
	{
		id: "witch",
		title: "Hexe",
		images: ["/og-booklet/witch-rt0.png", "/og-booklet/witch-i0.png", "/gear-card-base-game/gear-card-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 3`, GEAR_CARD_BASE_GAME],
	},
	{
		id: "thorald",
		title: "Prinz Thorald",
		images: ["/og-booklet/thorald-rt0.png", "/og-booklet/thorald-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 3`],
	},
	{
		id: "shield-dwarfs",
		title: "Schildzwerge",
		images: ["/og-booklet/shield-dwarfs-rt0.png", "/og-booklet/shield-dwarfs-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 3`],
	},
	{
		id: "golden-shields",
		title: "Die goldenen Schilde",
		images: ["/og-booklet/golden-shields-rt0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 3`],
	},
	{
		id: "helmet",
		title: "Helm",
		images: ["/og-booklet/helmet-rt0.png", "/og-booklet/gear-i0.png", "/gear-card-base-game/gear-card-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1/3`, GEAR_CARD_BASE_GAME],
	},
	{
		id: "shield",
		title: "Schild",
		images: ["/og-booklet/gear-i0.png", "/gear-card-base-game/gear-card-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`, GEAR_CARD_BASE_GAME],
	},
	{
		id: "bow",
		title: "Bogen",
		images: ["/og-booklet/gear-i0.png", "/gear-card-base-game/gear-card-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`, GEAR_CARD_BASE_GAME],
	},
	{
		id: "falcon",
		title: "Falke",
		images: ["/og-booklet/gear-i0.png", "/gear-card-base-game/gear-card-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`, GEAR_CARD_BASE_GAME],
	},
	{
		id: "drinking-hose",
		title: "Trinkschlauch",
		images: ["/og-booklet/gear-i0.png", "/gear-card-base-game/gear-card-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`, GEAR_CARD_BASE_GAME],
	},
	{
		id: "telescope",
		title: "Fernrohr",
		images: ["/og-booklet/gear-i0.png", "/gear-card-base-game/gear-card-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`, GEAR_CARD_BASE_GAME],
	},
	{
		id: "which-drank",
		title: "Trank der Hexe",
		images: ["/og-booklet/gear-i0.png", "/gear-card-base-game/gear-card-i0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 1`, GEAR_CARD_BASE_GAME],
	},
	{
		id: "checklist",
		title: "Checkliste",
		images: ["/og-booklet/checklist-rt0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 3`],
	},
	{
		id: "rank-numbers",
		title: "Rangzahlen",
		images: ["/og-booklet/rank-number-rt0.png"],
		source: [`${BASE_GAME_ACCOMPANYING_BOOKLET}, S. 3`],
	},
];

export default baseGameBookletData;
