import {ManualData} from "./man-data";

const NORTH_BOOKLET: string = "Begleitheft - Die Reise in den Norden";

const northBookletData: ManualData[] = [
	{
		id: "card-required-material",
		title: "Karte 'Benötigtes Material aus dem Grundspiel'",
		images: ["/north-booklet/card-required-material-north-rt0.png"],
		source: [`${NORTH_BOOKLET}, S. 1`],
	},
	{
		id: "the-hero-dwarf",
		title: "Der Held Zwerg (Die Reise in den Norden)",
		images: ["/north-booklet/north-dwarf-rt0.png"],
		source: [`${NORTH_BOOKLET}, S. 1`],
	},
	{
		id: "coat-of-arms",
		title: "Die Heldenwappen",
		images: ["/north-booklet/coat-of-arms-rt0.png", "/north-booklet/coat-of-arms-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 1`],
	},
	{
		id: "small-cards-north",
		title: "Kleine Karten (Die Reise in den Norden)",
		images: ["/north-booklet/small-cards-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "big-cards-north",
		title: "Große Karten (Die Reise in den Norden)",
		images: ["/north-booklet/cards-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "sea-warrior",
		title: "Heldentafel 'Seekrieger bzw. Seekriegerin'",
		images: ["/north-booklet/sea-warrior-i0.png", "/north-booklet/north-dwarf-rt0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "gear-card-north",
		title: "Ausrüstungstafel (Nord-Spielplan)",
		images: ["/north-booklet/gear-card-north-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "gear-card-hadria",
		title: "Ausrüstungstafel (Hadria-Spielplan)",
		images: ["/north-booklet/gear-card-hadria-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "bard",
		title: "Barde",
		images: ["/north-booklet/bard-ship-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "ship",
		title: "Schiff",
		images: ["/north-booklet/bard-ship-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "merrik",
		title: "Merrik",
		images: ["/north-booklet/misc-figures-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "grenolin",
		title: "Grenolin",
		images: ["/north-booklet/misc-figures-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "garz",
		title: "Garz",
		images: ["/north-booklet/misc-figures-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "vision",
		title: "Vision",
		images: ["/north-booklet/misc-figures-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "kenvilar",
		title: "Kenvilar",
		images: ["/north-booklet/misc-figures-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "arkteron",
		title: "Arkteron",
		images: ["/north-booklet/misc-figures-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "tars",
		title: "Taren",
		images: ["/north-booklet/misc-figures-i0.png", "/north-booklet/tar-portal-storm-shield-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "silber-dwarfs",
		title: "Silberzwerge",
		images: ["/north-booklet/misc-figures-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "fire-wizard",
		title: "Zauberer des Feuers",
		images: ["/north-booklet/misc-figures-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "tower-wizards",
		title: "Zauberer des Turms",
		images: ["/north-booklet/misc-figures-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "sea-giant",
		title: "Seeriese",
		images: ["/north-booklet/misc-figures-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "qurun",
		title: "Qurun",
		images: ["/north-booklet/misc-figures-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "special-figures",
		title: "Besondere Figuren für eure eigenen Legenden",
		images: ["/north-booklet/special-figures-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "north-well",
		title: "Nord-Brunnen (für die Variante)",
		images: ["/north-booklet/north-well-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "north-dices",
		title: "Würfel (Die Reise in den Norden)",
		images: ["/north-booklet/dices-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "wood-discs",
		title: "Holzscheiben bzw,. Holzwürfel",
		images: ["/north-booklet/north-discs-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "nerax",
		title: "Nerax",
		images: ["/north-booklet/creatures-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "sea-troll",
		title: "Meerestrolle",
		images: ["/north-booklet/creatures-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "arrog",
		title: "Arrogs",
		images: ["/north-booklet/creatures-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "fire-spell",
		title: "Zauber des Feuers",
		images: ["/north-booklet/small-cards-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "tower-spell",
		title: "Zauber des Turms",
		images: ["/north-booklet/small-cards-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "contract-cards",
		title: "Auftragskarten",
		images: ["/north-booklet/small-cards-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 2`],
	},
	{
		id: "north-fog-platelets",
		title: "Nebelplättchen (Die Reise in den Norden)",
		images: ["/north-booklet/north-fog-platelets-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 3`],
	},
	{
		id: "north-creature-platelets",
		title: "Nord-Kreaturenplättchen",
		images: ["/north-booklet/north-creature-platelets-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 3`],
	},
	{
		id: "coat-of-arms-platelets",
		title: "Wappenplättchen",
		images: ["/north-booklet/coat-of-arms-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 3`],
	},
	{
		id: "eternal-fire",
		title: "Ewiges Feuer",
		images: ["/north-booklet/eternal-fire-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 3`],
	},
	{
		id: "creature-bar-5-6-players",
		title: "Kreaturenleisten für 5 bzw. 6 Helden",
		images: ["/north-booklet/creature-bar-5-6-players-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 3`],
	},
	{
		id: "tar-symbol",
		title: "Tarensymbol",
		images: ["/north-booklet/tar-portal-storm-shield-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 3`],
	},
	{
		id: "barrels",
		title: "Fässer",
		images: ["/north-booklet/hour-glass-barrel-star-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 3`],
	},
	{
		id: "oktohan",
		title: "Oktohan",
		images: ["/north-booklet/oktohan-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 3`],
	},
	{
		id: "jewlery",
		title: "Schmuckkette",
		images: ["/north-booklet/treasure-jewlery-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 3`],
	},
	{
		id: "treasure",
		title: "Truhe",
		images: ["/north-booklet/treasure-jewlery-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 3`],
	},
	{
		id: "black-crystal",
		title: "Schwarzer Kristall",
		images: ["/north-booklet/dark-cristal-marker-flood-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 3`],
	},
	{
		id: "marker-north",
		title: "Markierungsring",
		images: ["/north-booklet/dark-cristal-marker-flood-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 3`],
	},
	{
		id: "flood-platelet",
		title: "Flutplättchen",
		images: ["/north-booklet/dark-cristal-marker-flood-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 3`],
	},
	{
		id: "wreck-platelet",
		title: "Wrackplättchen",
		images: ["/north-booklet/wreck-feather-platelets-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 3`],
	},
	{
		id: "feather-platelet",
		title: "Federplättchen",
		images: ["/north-booklet/wreck-feather-platelets-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 3`],
	},
	{
		id: "north-gameplan",
		title: "Nord-Spielplan",
		images: ["/north-booklet/north-gameplan-rt0.png"],
		source: [`${NORTH_BOOKLET}, S. 4`],
	},
	{
		id: "hadria-gameplan",
		title: "Hadria-Spielplan",
		images: ["/north-booklet/hadria-gameplan-rt0.png"],
		source: [`${NORTH_BOOKLET}, S. 4`],
	},
	{
		id: "hall-of-fame-and-bard",
		title: "Ruhmeshalle und Barde",
		images: ["/north-booklet/hall-of-fame-bard-rt0.png"],
		source: [`${NORTH_BOOKLET}, S. 4`],
	},
	{
		id: "ship-movement",
		title: "Shiffsbewegung",
		images: ["/north-booklet/ship-movement-rt0.png"],
		source: [`${NORTH_BOOKLET}, S. 4`],
	},
	{
		id: "cliffs",
		title: "Klippen",
		images: ["/north-booklet/cliffs-rt0.png"],
		source: [`${NORTH_BOOKLET}, S. 4`],
	},
	{
		id: "leave-enter-ship-north-booklet",
		title: "Von/An Bord gehen",
		images: ["/north-booklet/leave-enter-ship-rt0.png"],
		source: [`${NORTH_BOOKLET}, S. 4`],
	},
	{
		id: "boats-north-booklet",
		title: "Boote",
		images: ["/north-booklet/boats-rt0.png"],
		source: [`${NORTH_BOOKLET}, S. 4`],
	},
	{
		id: "wind-and-storm-cards",
		title: "Windkarten bzw. Sturmkarten",
		images: ["/north-booklet/wind-and-storm-cards-rt0.png", "/north-booklet/small-cards-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 4`],
	},
	{
		id: "sailing-examples",
		title: "Beispiele fürs Segeln",
		images: ["/north-booklet/ship-board-rt0.png", "/north-booklet/sailing-examples-rt0.png"],
		source: [`${NORTH_BOOKLET}, S. 5`],
	},
	{
		id: "ship-board-booklet",
		title: "Schiffstafel",
		images: ["/north-booklet/ship-board-rt0.png", "/north-booklet/ship-board-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 5`],
	},
	{
		id: "sea-creatures",
		title: "Meereskreaturen",
		images: ["/north-booklet/sea-creatures-rt0.png", "/north-booklet/creatures-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 5`],
	},
	{
		id: "gifts-of-the-north",
		title: "Die Gaben des Nordens",
		images: [
			"/north-booklet/gifts-of-the-north-rt0.png",
			"/north-booklet/gifts-of-the-north-i0.png",
			"/north-booklet/marten-rt0.png",
			"/north-booklet/nix-dust-rt0.png",
			"/north-booklet/hadric-compass-rt0.png",
		],
		source: [`${NORTH_BOOKLET}, S. 6`],
	},
	{
		id: "marten",
		title: "Diebischer Streifenmarder",
		images: ["/north-booklet/marten-rt0.png", "/north-booklet/gifts-of-the-north-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 6`],
	},
	{
		id: "hadric-compass",
		title: "Der Hadrische Kompass",
		images: ["/north-booklet/hadric-compass-rt0.png", "/north-booklet/gifts-of-the-north-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 6`],
	},
	{
		id: "nix-dust",
		title: "Nixenstaub",
		images: ["/north-booklet/nix-dust-rt0.png", "/north-booklet/gifts-of-the-north-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 6`],
	},
	{
		id: "hadric-hourglass",
		title: "Das Hadrische Stundenglas",
		images: ["/north-booklet/hadric-hour-glass-rt0.png", "/north-booklet/hour-glass-barrel-star-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 6`],
	},
	{
		id: "storm-shield",
		title: "Sturmschild",
		images: ["/north-booklet/storm-shield-rt0.png", "/north-booklet/tar-portal-storm-shield-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 6`],
	},
	{
		id: "wood-and-iron",
		title: "Holz und Eisen",
		images: ["/north-booklet/wood-and-iron-rt0.png", "/north-booklet/wood-iron-shell-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 6`],
	},
	{
		id: "shells",
		title: "Muscheln",
		images: ["/north-booklet/shells-rt0.png", "/north-booklet/wood-iron-shell-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 6`],
	},
	{
		id: "magic-weapons",
		title: "Die magischen Waffen",
		images: [
			"/north-booklet/magic-weapons-rt0.png",
			"/north-booklet/magic-weapons-i0.png",
			"/north-booklet/orweyns-hammer-rt0.png",
			"/north-booklet/varlion-flame-sword-rt0.png",
			"/north-booklet/varatans-helmet-rt0.png",
		],
		source: [`${NORTH_BOOKLET}, S. 6`],
	},
	{
		id: "orweyns-hammer",
		title: "Orweyns Hammer der Stärke",
		images: ["/north-booklet/orweyns-hammer-rt0.png", "/north-booklet/magic-weapons-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 6`],
	},
	{
		id: "varlion-flame-sword",
		title: "Varlion das Flammenschwert",
		images: ["/north-booklet/varlion-flame-sword-rt0.png", "/north-booklet/magic-weapons-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 6`],
	},
	{
		id: "varatans-helmet",
		title: "Varatans Helm der Macht",
		images: ["/north-booklet/varatans-helmet-rt0.png", "/north-booklet/magic-weapons-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 6`],
	},
	{
		id: "storm-platelets",
		title: "Unwetterplättchen (Bild fehlt)",
		images: ["/north-booklet/storm-platelets-rt0.png"],
		source: [`${NORTH_BOOKLET}, S. 6`],
	},
	{
		id: "wreck-platelets",
		title: "Wrackplättchen",
		images: ["/north-booklet/wreck-platelets-rt0.png", "/north-booklet/wreck-platelets-rt1.png", "/north-booklet/wreck-feather-platelets-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 6/7`],
	},
	{
		id: "snow-platelets",
		title: "Schneeplättchen",
		images: ["/north-booklet/snow-platelets-rt0.png", "/north-booklet/snow-platelets-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 7`],
	},
	{
		id: "portals",
		title: "Portale",
		images: ["/north-booklet/portals-rt0.png", "/north-booklet/tar-portal-storm-shield-i0.png"],
		source: [`${NORTH_BOOKLET}, S. 7`],
	},
	{
		id: "dawn-field-north",
		title: "Das Sonnenaufgang-Feld (Nord-Spielplan)",
		images: ["/north-booklet/dawn-field-rt0.png", "/north-booklet/dawn-field-rt1.png"],
		source: [`${NORTH_BOOKLET}, S. 7`],
	},
	{
		id: "game-variants-north",
		title: "Spielvarianten (Nord-Spielplan)",
		images: [
			"/north-booklet/game-variants-north-rt0.png",
			"/north-booklet/north-well-i0.png",
			"/north-booklet/misc-figures-i0.png",
			"/north-booklet/bard-ship-i0.png",
		],
		source: [`${NORTH_BOOKLET}, S. 7`],
	},
	{
		id: "north-game-with-5-6-players",
		title: "Die Reise in den Norden für 5-6 Helden",
		images: ["/north-booklet/north-game-with-5-6-players-rt0.png", "/north-booklet/north-game-with-5-6-players-rt1.png"],
		source: [`${NORTH_BOOKLET}, S. 8`],
	},
];

export default northBookletData;
